

#include "device_driver_subsystem.h"


/*
 * Extern variables are automatically
 * generated by the driver manifest
 * processing script. It will automatically
 * generate a C file with an array of
 * drivers and a variable containing
 * the number of drivers in the array.
 */
extern driver_t *_device_driver_list;
extern int _num_drivers;


void init_dev_drivers()
{

}